-- Global product-feedback suggestions (not site-scoped).

CREATE TABLE IF NOT EXISTS "appFeedback" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "entryNumber" integer GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  "body" text NOT NULL,
  "createdBy" uuid NOT NULL REFERENCES "users" ("id"),
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "appFeedback_body_len"
    CHECK (char_length(trim("body")) > 0 AND char_length("body") <= 4000)
);

CREATE INDEX IF NOT EXISTS "appFeedback_createdAt_idx"
  ON "appFeedback" ("createdAt" DESC);
