-- Seed detailed single-asset report (QR top-right) for every site, targetApp = assets

INSERT INTO "reportDefinition" ("key", "name", "siteId", "targetAppKey", "sql", "layout", "createdBy")
SELECT
  'asset-detail-report',
  'Asset-Report (ausführlich)',
  s."id",
  'assets',
  $report_sql$
SELECT
  a."id",
  a."key",
  a."name",
  a."key" AS "qrValue",
  CASE a."type"
    WHEN 'site' THEN 'Standort'
    WHEN 'structure' THEN 'Struktur'
    WHEN 'line' THEN 'Linie'
    WHEN 'maintenanceObject' THEN 'Instandhaltungsobjekt'
    ELSE a."type"
  END AS "typeLabel",
  a."type",
  s."key" AS "siteKey",
  s."name" AS "siteName",
  parent."key" AS "parentAssetKey",
  parent."name" AS "parentAssetName",
  CASE
    WHEN parent."id" IS NULL THEN '—'
    ELSE COALESCE(parent."key", '') || ' — ' || COALESCE(parent."name", '')
  END AS "parentLabel",
  COALESCE(a."serialNumber", '—') AS "serialNumber",
  COALESCE(a."manufacturer", '—') AS "manufacturer",
  COALESCE(to_char(a."buildDate", 'DD.MM.YYYY'), '—') AS "buildDate",
  CASE
    WHEN cc."id" IS NULL THEN '—'
    ELSE COALESCE(cc."key", '') || ' — ' || COALESCE(cc."name", '')
  END AS "costCenterLabel",
  CASE
    WHEN clf."id" IS NULL THEN '—'
    ELSE COALESCE(clf."key", '') || ' — ' || COALESCE(clf."name", '')
  END AS "classificationLabel",
  COALESCE(a."remark", '') AS "remark",
  COALESCE(doc_counts."documentCount", 0)::int AS "documentCount",
  COALESCE(wo_counts."workOrderCount", 0)::int AS "workOrderCount",
  COALESCE(ip_counts."inspectionPointCount", 0)::int AS "inspectionPointCount",
  to_char(a."createdAt", 'DD.MM.YYYY HH24:MI') AS "createdAt",
  COALESCE(created_by."loginName", a."createdBy"::text) AS "createdBy",
  to_char(a."updatedAt", 'DD.MM.YYYY HH24:MI') AS "updatedAt",
  COALESCE(updated_by."loginName", a."updatedBy"::text) AS "updatedBy"
FROM "asset" a
JOIN "site" s ON s."id" = a."siteId"
LEFT JOIN "asset" parent ON parent."id" = a."parentAssetId"
LEFT JOIN "costCenter" cc ON cc."id" = a."costCenterId"
LEFT JOIN "classification" clf ON clf."id" = a."classificationId"
LEFT JOIN "users" created_by ON created_by."id" = a."createdBy"
LEFT JOIN "users" updated_by ON updated_by."id" = a."updatedBy"
LEFT JOIN (
  SELECT dl."entityId" AS "assetId", COUNT(*)::int AS "documentCount"
  FROM "documentLink" dl
  WHERE dl."entityType" = 'asset'
  GROUP BY dl."entityId"
) doc_counts ON doc_counts."assetId" = a."id"
LEFT JOIN (
  SELECT wo."assetId", COUNT(*)::int AS "workOrderCount"
  FROM "workOrder" wo
  GROUP BY wo."assetId"
) wo_counts ON wo_counts."assetId" = a."id"
LEFT JOIN (
  SELECT ip."assetId", COUNT(*)::int AS "inspectionPointCount"
  FROM "inspectionPoint" ip
  GROUP BY ip."assetId"
) ip_counts ON ip_counts."assetId" = a."id"
WHERE a."id" = {{recordId}}
$report_sql$,
  $report_layout${
  "header": { "height": 108, "firstPageOnly": false },
  "groupHeader": { "height": 16 },
  "detail": { "height": 400 },
  "groupFooter": { "height": 16 },
  "footer": { "height": 32 },
  "grouping": {
    "enabled": false,
    "field": "",
    "sort": "asc",
    "granularity": "day",
    "dateFormat": "YYYY-MM-DD"
  },
  "filters": [],
  "elements": [
    {
      "id": "a0000001-0001-4000-8000-000000000001",
      "section": "header",
      "text": "Asset-Report",
      "x": 40,
      "y": 18,
      "width": 360,
      "height": 22,
      "fontSize": 20,
      "align": "left",
      "bold": true,
      "italic": false,
      "underline": false,
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "a0000001-0001-4000-8000-000000000002",
      "section": "header",
      "text": "{{key}}  —  {{name}}",
      "x": 40,
      "y": 48,
      "width": 400,
      "height": 18,
      "fontSize": 12,
      "align": "left",
      "bold": false,
      "italic": false,
      "underline": false,
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "a0000001-0001-4000-8000-000000000003",
      "section": "header",
      "text": "Standort: {{siteName}} ({{siteKey}})",
      "x": 40,
      "y": 72,
      "width": 400,
      "height": 16,
      "fontSize": 10,
      "align": "left",
      "bold": false,
      "italic": true,
      "underline": false,
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "a0000001-0001-4000-8000-000000000004",
      "section": "header",
      "text": "QR",
      "x": 483,
      "y": 16,
      "width": 76,
      "height": 76,
      "fontSize": 10,
      "align": "left",
      "bold": false,
      "italic": false,
      "underline": false,
      "kind": "qr",
      "sourceField": "qrValue",
      "dateFormat": ""
    },
    {
      "id": "a0000001-0001-4000-8000-000000000010",
      "section": "detail",
      "text": "Stammdaten",
      "x": 40,
      "y": 8,
      "width": 240,
      "height": 16,
      "fontSize": 12,
      "align": "left",
      "bold": true,
      "italic": false,
      "underline": true,
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "a0000001-0001-4000-8000-000000000011",
      "section": "detail",
      "text": "Typ",
      "x": 40,
      "y": 34,
      "width": 100,
      "height": 16,
      "fontSize": 9,
      "align": "left",
      "bold": true,
      "italic": false,
      "underline": false,
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "a0000001-0001-4000-8000-000000000012",
      "section": "detail",
      "text": "{{typeLabel}}",
      "x": 140,
      "y": 34,
      "width": 150,
      "height": 16,
      "fontSize": 10,
      "align": "left",
      "bold": false,
      "italic": false,
      "underline": false,
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "a0000001-0001-4000-8000-000000000013",
      "section": "detail",
      "text": "Schlüssel",
      "x": 310,
      "y": 34,
      "width": 90,
      "height": 16,
      "fontSize": 9,
      "align": "left",
      "bold": true,
      "italic": false,
      "underline": false,
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "a0000001-0001-4000-8000-000000000014",
      "section": "detail",
      "text": "{{key}}",
      "x": 400,
      "y": 34,
      "width": 155,
      "height": 16,
      "fontSize": 10,
      "align": "left",
      "bold": false,
      "italic": false,
      "underline": false,
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "a0000001-0001-4000-8000-000000000015",
      "section": "detail",
      "text": "Name",
      "x": 40,
      "y": 56,
      "width": 100,
      "height": 16,
      "fontSize": 9,
      "align": "left",
      "bold": true,
      "italic": false,
      "underline": false,
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "a0000001-0001-4000-8000-000000000016",
      "section": "detail",
      "text": "{{name}}",
      "x": 140,
      "y": 56,
      "width": 415,
      "height": 16,
      "fontSize": 10,
      "align": "left",
      "bold": false,
      "italic": false,
      "underline": false,
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "a0000001-0001-4000-8000-000000000017",
      "section": "detail",
      "text": "Standort",
      "x": 40,
      "y": 78,
      "width": 100,
      "height": 16,
      "fontSize": 9,
      "align": "left",
      "bold": true,
      "italic": false,
      "underline": false,
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "a0000001-0001-4000-8000-000000000018",
      "section": "detail",
      "text": "{{siteName}} ({{siteKey}})",
      "x": 140,
      "y": 78,
      "width": 415,
      "height": 16,
      "fontSize": 10,
      "align": "left",
      "bold": false,
      "italic": false,
      "underline": false,
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "a0000001-0001-4000-8000-000000000019",
      "section": "detail",
      "text": "Übergeordnet",
      "x": 40,
      "y": 100,
      "width": 100,
      "height": 16,
      "fontSize": 9,
      "align": "left",
      "bold": true,
      "italic": false,
      "underline": false,
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "a0000001-0001-4000-8000-000000000020",
      "section": "detail",
      "text": "{{parentLabel}}",
      "x": 140,
      "y": 100,
      "width": 415,
      "height": 16,
      "fontSize": 10,
      "align": "left",
      "bold": false,
      "italic": false,
      "underline": false,
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "a0000001-0001-4000-8000-000000000021",
      "section": "detail",
      "text": "Seriennummer",
      "x": 40,
      "y": 122,
      "width": 100,
      "height": 16,
      "fontSize": 9,
      "align": "left",
      "bold": true,
      "italic": false,
      "underline": false,
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "a0000001-0001-4000-8000-000000000022",
      "section": "detail",
      "text": "{{serialNumber}}",
      "x": 140,
      "y": 122,
      "width": 150,
      "height": 16,
      "fontSize": 10,
      "align": "left",
      "bold": false,
      "italic": false,
      "underline": false,
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "a0000001-0001-4000-8000-000000000023",
      "section": "detail",
      "text": "Hersteller",
      "x": 310,
      "y": 122,
      "width": 90,
      "height": 16,
      "fontSize": 9,
      "align": "left",
      "bold": true,
      "italic": false,
      "underline": false,
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "a0000001-0001-4000-8000-000000000024",
      "section": "detail",
      "text": "{{manufacturer}}",
      "x": 400,
      "y": 122,
      "width": 155,
      "height": 16,
      "fontSize": 10,
      "align": "left",
      "bold": false,
      "italic": false,
      "underline": false,
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "a0000001-0001-4000-8000-000000000025",
      "section": "detail",
      "text": "Baujahr",
      "x": 40,
      "y": 144,
      "width": 100,
      "height": 16,
      "fontSize": 9,
      "align": "left",
      "bold": true,
      "italic": false,
      "underline": false,
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "a0000001-0001-4000-8000-000000000026",
      "section": "detail",
      "text": "{{buildDate}}",
      "x": 140,
      "y": 144,
      "width": 150,
      "height": 16,
      "fontSize": 10,
      "align": "left",
      "bold": false,
      "italic": false,
      "underline": false,
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "a0000001-0001-4000-8000-000000000027",
      "section": "detail",
      "text": "Klassifizierung",
      "x": 310,
      "y": 144,
      "width": 90,
      "height": 16,
      "fontSize": 9,
      "align": "left",
      "bold": true,
      "italic": false,
      "underline": false,
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "a0000001-0001-4000-8000-000000000028",
      "section": "detail",
      "text": "{{classificationLabel}}",
      "x": 400,
      "y": 144,
      "width": 155,
      "height": 16,
      "fontSize": 10,
      "align": "left",
      "bold": false,
      "italic": false,
      "underline": false,
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "a0000001-0001-4000-8000-000000000029",
      "section": "detail",
      "text": "Kostenstelle",
      "x": 40,
      "y": 166,
      "width": 100,
      "height": 16,
      "fontSize": 9,
      "align": "left",
      "bold": true,
      "italic": false,
      "underline": false,
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "a0000001-0001-4000-8000-000000000030",
      "section": "detail",
      "text": "{{costCenterLabel}}",
      "x": 140,
      "y": 166,
      "width": 415,
      "height": 16,
      "fontSize": 10,
      "align": "left",
      "bold": false,
      "italic": false,
      "underline": false,
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "a0000001-0001-4000-8000-000000000040",
      "section": "detail",
      "text": "Kennzahlen",
      "x": 40,
      "y": 198,
      "width": 240,
      "height": 16,
      "fontSize": 12,
      "align": "left",
      "bold": true,
      "italic": false,
      "underline": true,
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "a0000001-0001-4000-8000-000000000041",
      "section": "detail",
      "text": "Dokumente",
      "x": 40,
      "y": 224,
      "width": 100,
      "height": 16,
      "fontSize": 9,
      "align": "left",
      "bold": true,
      "italic": false,
      "underline": false,
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "a0000001-0001-4000-8000-000000000042",
      "section": "detail",
      "text": "{{documentCount}}",
      "x": 140,
      "y": 224,
      "width": 60,
      "height": 16,
      "fontSize": 10,
      "align": "left",
      "bold": false,
      "italic": false,
      "underline": false,
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "a0000001-0001-4000-8000-000000000043",
      "section": "detail",
      "text": "Aufträge",
      "x": 220,
      "y": 224,
      "width": 70,
      "height": 16,
      "fontSize": 9,
      "align": "left",
      "bold": true,
      "italic": false,
      "underline": false,
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "a0000001-0001-4000-8000-000000000044",
      "section": "detail",
      "text": "{{workOrderCount}}",
      "x": 290,
      "y": 224,
      "width": 60,
      "height": 16,
      "fontSize": 10,
      "align": "left",
      "bold": false,
      "italic": false,
      "underline": false,
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "a0000001-0001-4000-8000-000000000045",
      "section": "detail",
      "text": "Prüfstellen",
      "x": 370,
      "y": 224,
      "width": 80,
      "height": 16,
      "fontSize": 9,
      "align": "left",
      "bold": true,
      "italic": false,
      "underline": false,
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "a0000001-0001-4000-8000-000000000046",
      "section": "detail",
      "text": "{{inspectionPointCount}}",
      "x": 450,
      "y": 224,
      "width": 80,
      "height": 16,
      "fontSize": 10,
      "align": "left",
      "bold": false,
      "italic": false,
      "underline": false,
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "a0000001-0001-4000-8000-000000000050",
      "section": "detail",
      "text": "Bemerkung",
      "x": 40,
      "y": 256,
      "width": 240,
      "height": 16,
      "fontSize": 12,
      "align": "left",
      "bold": true,
      "italic": false,
      "underline": true,
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "a0000001-0001-4000-8000-000000000051",
      "section": "detail",
      "text": "{{remark}}",
      "x": 40,
      "y": 280,
      "width": 515,
      "height": 48,
      "fontSize": 10,
      "align": "left",
      "bold": false,
      "italic": false,
      "underline": false,
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "a0000001-0001-4000-8000-000000000060",
      "section": "detail",
      "text": "Protokoll",
      "x": 40,
      "y": 338,
      "width": 240,
      "height": 16,
      "fontSize": 12,
      "align": "left",
      "bold": true,
      "italic": false,
      "underline": true,
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "a0000001-0001-4000-8000-000000000061",
      "section": "detail",
      "text": "Erstellt",
      "x": 40,
      "y": 362,
      "width": 100,
      "height": 16,
      "fontSize": 9,
      "align": "left",
      "bold": true,
      "italic": false,
      "underline": false,
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "a0000001-0001-4000-8000-000000000062",
      "section": "detail",
      "text": "{{createdAt}}  ·  {{createdBy}}",
      "x": 140,
      "y": 362,
      "width": 415,
      "height": 16,
      "fontSize": 10,
      "align": "left",
      "bold": false,
      "italic": false,
      "underline": false,
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "a0000001-0001-4000-8000-000000000063",
      "section": "detail",
      "text": "Geändert",
      "x": 40,
      "y": 382,
      "width": 100,
      "height": 16,
      "fontSize": 9,
      "align": "left",
      "bold": true,
      "italic": false,
      "underline": false,
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "a0000001-0001-4000-8000-000000000064",
      "section": "detail",
      "text": "{{updatedAt}}  ·  {{updatedBy}}",
      "x": 140,
      "y": 382,
      "width": 415,
      "height": 16,
      "fontSize": 10,
      "align": "left",
      "bold": false,
      "italic": false,
      "underline": false,
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "a0000001-0001-4000-8000-000000000070",
      "section": "footer",
      "text": "Athene CMMS  ·  Asset-Report  ·  Seite {{_pageNumber}}",
      "x": 40,
      "y": 8,
      "width": 400,
      "height": 16,
      "fontSize": 9,
      "align": "left",
      "bold": false,
      "italic": false,
      "underline": false,
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "a0000001-0001-4000-8000-000000000071",
      "section": "footer",
      "text": "ID: {{id}}",
      "x": 360,
      "y": 8,
      "width": 195,
      "height": 16,
      "fontSize": 8,
      "align": "right",
      "bold": false,
      "italic": false,
      "underline": false,
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    }
  ]
}$report_layout$::jsonb,
  creator."id"
FROM "site" s
CROSS JOIN LATERAL (
  SELECT u."id"
  FROM "users" u
  ORDER BY CASE WHEN u."loginName" = 'admin' THEN 0 ELSE 1 END, u."loginName"
  LIMIT 1
) creator
WHERE NOT EXISTS (
  SELECT 1
  FROM "reportDefinition" d
  WHERE d."siteId" = s."id"
    AND d."key" = 'asset-detail-report'
);
