-- Refresh work-order-detail-report: full fields, thematic sections with hlines, asset QR + key top-right

UPDATE "reportDefinition"
SET
  "name" = 'Auftrags-Report',
  "sql" = $report_sql$
SELECT
  wo."id",
  wo."orderNumber",
  wo."name",
  COALESCE(wo."description", '') AS "description",
  wo."status",
  CASE wo."status"
    WHEN 'open' THEN 'Offen'
    WHEN 'assigned' THEN 'Zugewiesen'
    WHEN 'started' THEN 'Gestartet'
    WHEN 'paused' THEN 'Pausiert'
    WHEN 'continued' THEN 'Aufgenommen'
    WHEN 'ended' THEN 'Beendet'
    WHEN 'done' THEN 'Erledigt'
    WHEN 'cancelled' THEN 'Storniert'
    ELSE wo."status"
  END AS "statusLabel",
  wo."orderType",
  COALESCE(wot."name", wo."orderType") AS "orderTypeLabel",
  COALESCE(a."key", '') AS "qrValue",
  COALESCE(a."key", '—') AS "assetKey",
  COALESCE(a."name", '—') AS "assetName",
  CASE
    WHEN a."id" IS NULL THEN '—'
    ELSE COALESCE(a."key", '') || ' — ' || COALESCE(a."name", '')
  END AS "assetLabel",
  s."key" AS "siteKey",
  s."name" AS "siteName",
  CASE
    WHEN s."id" IS NULL THEN '—'
    ELSE COALESCE(s."key", '') || ' — ' || COALESCE(s."name", '')
  END AS "siteLabel",
  CASE
    WHEN cc."id" IS NULL THEN '—'
    ELSE COALESCE(cc."key", '') || ' — ' || COALESCE(cc."name", '')
  END AS "costCenterLabel",
  CASE
    WHEN clf."id" IS NULL THEN '—'
    ELSE COALESCE(clf."key", '') || ' — ' || COALESCE(clf."name", '')
  END AS "classificationLabel",
  CASE
    WHEN wg."id" IS NULL THEN '—'
    ELSE COALESCE(wg."key", '') || ' — ' || COALESCE(wg."name", '')
  END AS "workgroupLabel",
  COALESCE((
    SELECT string_agg(
      COALESCE(e."key", '') || ' — ' || COALESCE(e."name", ''),
      ', ' ORDER BY e."key"
    )
    FROM "workOrderResponsibleEmployee" wor
    JOIN "employee" e ON e."id" = wor."employeeId"
    WHERE wor."workOrderId" = wo."id"
  ), '—') AS "responsibleLabel",
  COALESCE(to_char(wo."plannedStart", 'DD.MM.YYYY HH24:MI'), '—') AS "plannedStart",
  COALESCE(to_char(wo."plannedEnd", 'DD.MM.YYYY HH24:MI'), '—') AS "plannedEnd",
  COALESCE(wo."plannedDurationMinutes"::text, '—') AS "plannedDurationMinutes",
  CASE
    WHEN p."id" IS NULL THEN '—'
    ELSE COALESCE(p."key", '') || ' — ' || COALESCE(p."name", '')
  END AS "problemLabel",
  CASE
    WHEN c."id" IS NULL THEN '—'
    ELSE COALESCE(c."key", '') || ' — ' || COALESCE(c."name", '')
  END AS "causeLabel",
  CASE
    WHEN r."id" IS NULL THEN '—'
    ELSE COALESCE(r."key", '') || ' — ' || COALESCE(r."name", '')
  END AS "remedyLabel",
  CASE
    WHEN dbe."id" IS NULL THEN '—'
    ELSE COALESCE(dbe."key", '') || ' — ' || COALESCE(dbe."name", '')
  END AS "doneByLabel",
  COALESCE(wo."pauseRemark", '') AS "pauseRemark",
  CASE
    WHEN orig."id" IS NULL THEN '—'
    ELSE '#' || orig."orderNumber"::text || ' — ' || COALESCE(orig."name", '')
  END AS "originalWoLabel",
  CASE
    WHEN mp."id" IS NULL THEN '—'
    ELSE COALESCE(mp."key", '') || ' — ' || COALESCE(mp."name", '')
  END AS "maintenancePlanLabel",
  CASE
    WHEN ir."id" IS NULL THEN '—'
    ELSE COALESCE(ir."key", '') || ' — ' || COALESCE(ir."name", '')
  END AS "inspectionRoundLabel",
  to_char(wo."createdAt", 'DD.MM.YYYY HH24:MI') AS "createdAt",
  COALESCE(created_by."loginName", wo."createdBy"::text) AS "createdBy",
  to_char(wo."updatedAt", 'DD.MM.YYYY HH24:MI') AS "updatedAt",
  COALESCE(updated_by."loginName", wo."updatedBy"::text) AS "updatedBy"
FROM "workOrder" wo
JOIN "site" s ON s."id" = wo."siteId"
LEFT JOIN "asset" a ON a."id" = wo."assetId"
LEFT JOIN "costCenter" cc ON cc."id" = wo."costCenterId"
LEFT JOIN "classification" clf ON clf."id" = wo."classificationId"
LEFT JOIN "workgroup" wg ON wg."id" = wo."workgroupId"
LEFT JOIN "workOrderType" wot ON wot."key" = wo."orderType" AND wot."siteId" = wo."siteId"
LEFT JOIN "problem" p ON p."id" = wo."problemId"
LEFT JOIN "cause" c ON c."id" = wo."causeId"
LEFT JOIN "remedy" r ON r."id" = wo."remedyId"
LEFT JOIN "employee" dbe ON dbe."id" = wo."doneBy"
LEFT JOIN "workOrder" orig ON orig."id" = wo."originalWo"
LEFT JOIN "maintenancePlan" mp ON mp."id" = wo."maintenancePlanId"
LEFT JOIN "inspectionRound" ir ON ir."id" = wo."inspectionRoundId"
LEFT JOIN "users" created_by ON created_by."id" = wo."createdBy"
LEFT JOIN "users" updated_by ON updated_by."id" = wo."updatedBy"
WHERE wo."id" = {{recordId}}
$report_sql$,
  "layout" = $report_layout${
  "header": { "height": 112, "firstPageOnly": false, "backgroundColor": "" },
  "groupHeader": { "height": 16, "backgroundColor": "" },
  "detail": { "height": 670, "backgroundColor": "" },
  "groupFooter": { "height": 16, "backgroundColor": "" },
  "footer": { "height": 32, "backgroundColor": "" },
  "grouping": {
    "enabled": false,
    "field": "",
    "sort": "asc",
    "granularity": "day",
    "dateFormat": "YYYY-MM-DD"
  },
  "filters": [],
  "elements": [
    {
      "id": "c0000001-0001-4000-8000-000000000001",
      "section": "header",
      "text": "Auftrags-Report",
      "x": 40,
      "y": 14,
      "width": 360,
      "height": 22,
      "fontSize": 20,
      "align": "left",
      "bold": true,
      "italic": false,
      "underline": false,
      "color": "#111827",
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "c0000001-0001-4000-8000-000000000002",
      "section": "header",
      "text": "#{{orderNumber}}  —  {{name}}",
      "x": 40,
      "y": 44,
      "width": 400,
      "height": 18,
      "fontSize": 12,
      "align": "left",
      "bold": false,
      "italic": false,
      "underline": false,
      "color": "#111827",
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "c0000001-0001-4000-8000-000000000003",
      "section": "header",
      "text": "Status: {{statusLabel}}  ·  Typ: {{orderTypeLabel}}",
      "x": 40,
      "y": 68,
      "width": 400,
      "height": 16,
      "fontSize": 10,
      "align": "left",
      "bold": false,
      "italic": true,
      "underline": false,
      "color": "#111827",
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "c0000001-0001-4000-8000-000000000004",
      "section": "header",
      "text": "QR",
      "x": 483,
      "y": 10,
      "width": 76,
      "height": 76,
      "fontSize": 10,
      "align": "left",
      "bold": false,
      "italic": false,
      "underline": false,
      "color": "#111827",
      "kind": "qr",
      "sourceField": "qrValue",
      "dateFormat": ""
    },
    {
      "id": "c0000001-0001-4000-8000-000000000005",
      "section": "header",
      "text": "{{assetKey}}",
      "x": 470,
      "y": 90,
      "width": 102,
      "height": 14,
      "fontSize": 8,
      "align": "center",
      "bold": false,
      "italic": false,
      "underline": false,
      "color": "#111827",
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "c0000001-0001-4000-8000-000000000010",
      "section": "detail",
      "text": "Stammdaten",
      "x": 40,
      "y": 8,
      "width": 240,
      "height": 16,
      "fontSize": 12,
      "align": "left",
      "bold": true,
      "italic": false,
      "underline": false,
      "color": "#111827",
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "c0000001-0001-4000-8000-000000000011",
      "section": "detail",
      "text": "Asset",
      "x": 40,
      "y": 30,
      "width": 120,
      "height": 14,
      "fontSize": 9,
      "align": "left",
      "bold": true,
      "italic": false,
      "underline": false,
      "color": "#111827",
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "c0000001-0001-4000-8000-000000000012",
      "section": "detail",
      "text": "{{assetLabel}}",
      "x": 160,
      "y": 30,
      "width": 395,
      "height": 14,
      "fontSize": 10,
      "align": "left",
      "bold": false,
      "italic": false,
      "underline": false,
      "color": "#111827",
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "c0000001-0001-4000-8000-000000000013",
      "section": "detail",
      "text": "Standort",
      "x": 40,
      "y": 50,
      "width": 120,
      "height": 14,
      "fontSize": 9,
      "align": "left",
      "bold": true,
      "italic": false,
      "underline": false,
      "color": "#111827",
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "c0000001-0001-4000-8000-000000000014",
      "section": "detail",
      "text": "{{siteLabel}}",
      "x": 160,
      "y": 50,
      "width": 395,
      "height": 14,
      "fontSize": 10,
      "align": "left",
      "bold": false,
      "italic": false,
      "underline": false,
      "color": "#111827",
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "c0000001-0001-4000-8000-000000000015",
      "section": "detail",
      "text": "Kostenstelle",
      "x": 40,
      "y": 70,
      "width": 120,
      "height": 14,
      "fontSize": 9,
      "align": "left",
      "bold": true,
      "italic": false,
      "underline": false,
      "color": "#111827",
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "c0000001-0001-4000-8000-000000000016",
      "section": "detail",
      "text": "{{costCenterLabel}}",
      "x": 160,
      "y": 70,
      "width": 395,
      "height": 14,
      "fontSize": 10,
      "align": "left",
      "bold": false,
      "italic": false,
      "underline": false,
      "color": "#111827",
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "c0000001-0001-4000-8000-000000000017",
      "section": "detail",
      "text": "Klassifizierung",
      "x": 40,
      "y": 90,
      "width": 120,
      "height": 14,
      "fontSize": 9,
      "align": "left",
      "bold": true,
      "italic": false,
      "underline": false,
      "color": "#111827",
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "c0000001-0001-4000-8000-000000000018",
      "section": "detail",
      "text": "{{classificationLabel}}",
      "x": 160,
      "y": 90,
      "width": 395,
      "height": 14,
      "fontSize": 10,
      "align": "left",
      "bold": false,
      "italic": false,
      "underline": false,
      "color": "#111827",
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "c0000001-0001-4000-8000-000000000019",
      "section": "detail",
      "text": "Fachgruppe",
      "x": 40,
      "y": 110,
      "width": 120,
      "height": 14,
      "fontSize": 9,
      "align": "left",
      "bold": true,
      "italic": false,
      "underline": false,
      "color": "#111827",
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "c0000001-0001-4000-8000-000000000020",
      "section": "detail",
      "text": "{{workgroupLabel}}",
      "x": 160,
      "y": 110,
      "width": 395,
      "height": 14,
      "fontSize": 10,
      "align": "left",
      "bold": false,
      "italic": false,
      "underline": false,
      "color": "#111827",
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "c0000001-0001-4000-8000-000000000021",
      "section": "detail",
      "text": "Verantwortliche",
      "x": 40,
      "y": 130,
      "width": 120,
      "height": 14,
      "fontSize": 9,
      "align": "left",
      "bold": true,
      "italic": false,
      "underline": false,
      "color": "#111827",
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "c0000001-0001-4000-8000-000000000022",
      "section": "detail",
      "text": "{{responsibleLabel}}",
      "x": 160,
      "y": 130,
      "width": 395,
      "height": 14,
      "fontSize": 10,
      "align": "left",
      "bold": false,
      "italic": false,
      "underline": false,
      "color": "#111827",
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "c0000001-0001-4000-8000-000000000023",
      "section": "detail",
      "text": "Beschreibung",
      "x": 40,
      "y": 154,
      "width": 515,
      "height": 14,
      "fontSize": 9,
      "align": "left",
      "bold": true,
      "italic": false,
      "underline": false,
      "color": "#111827",
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "c0000001-0001-4000-8000-000000000024",
      "section": "detail",
      "text": "{{description}}",
      "x": 40,
      "y": 172,
      "width": 515,
      "height": 44,
      "fontSize": 10,
      "align": "left",
      "bold": false,
      "italic": false,
      "underline": false,
      "color": "#111827",
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "c0000001-0001-4000-8000-000000000030",
      "section": "detail",
      "text": "",
      "x": 40,
      "y": 226,
      "width": 515,
      "height": 1,
      "fontSize": 10,
      "align": "left",
      "bold": false,
      "italic": false,
      "underline": false,
      "color": "#111827",
      "kind": "hline",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "c0000001-0001-4000-8000-000000000031",
      "section": "detail",
      "text": "Planung",
      "x": 40,
      "y": 238,
      "width": 240,
      "height": 16,
      "fontSize": 12,
      "align": "left",
      "bold": true,
      "italic": false,
      "underline": false,
      "color": "#111827",
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "c0000001-0001-4000-8000-000000000032",
      "section": "detail",
      "text": "Geplanter Start",
      "x": 40,
      "y": 260,
      "width": 120,
      "height": 14,
      "fontSize": 9,
      "align": "left",
      "bold": true,
      "italic": false,
      "underline": false,
      "color": "#111827",
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "c0000001-0001-4000-8000-000000000033",
      "section": "detail",
      "text": "{{plannedStart}}",
      "x": 160,
      "y": 260,
      "width": 180,
      "height": 14,
      "fontSize": 10,
      "align": "left",
      "bold": false,
      "italic": false,
      "underline": false,
      "color": "#111827",
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "c0000001-0001-4000-8000-000000000034",
      "section": "detail",
      "text": "Geplantes Ende",
      "x": 40,
      "y": 280,
      "width": 120,
      "height": 14,
      "fontSize": 9,
      "align": "left",
      "bold": true,
      "italic": false,
      "underline": false,
      "color": "#111827",
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "c0000001-0001-4000-8000-000000000035",
      "section": "detail",
      "text": "{{plannedEnd}}",
      "x": 160,
      "y": 280,
      "width": 180,
      "height": 14,
      "fontSize": 10,
      "align": "left",
      "bold": false,
      "italic": false,
      "underline": false,
      "color": "#111827",
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "c0000001-0001-4000-8000-000000000036",
      "section": "detail",
      "text": "Dauer (Min.)",
      "x": 40,
      "y": 300,
      "width": 120,
      "height": 14,
      "fontSize": 9,
      "align": "left",
      "bold": true,
      "italic": false,
      "underline": false,
      "color": "#111827",
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "c0000001-0001-4000-8000-000000000037",
      "section": "detail",
      "text": "{{plannedDurationMinutes}}",
      "x": 160,
      "y": 300,
      "width": 180,
      "height": 14,
      "fontSize": 10,
      "align": "left",
      "bold": false,
      "italic": false,
      "underline": false,
      "color": "#111827",
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "c0000001-0001-4000-8000-000000000040",
      "section": "detail",
      "text": "",
      "x": 40,
      "y": 324,
      "width": 515,
      "height": 1,
      "fontSize": 10,
      "align": "left",
      "bold": false,
      "italic": false,
      "underline": false,
      "color": "#111827",
      "kind": "hline",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "c0000001-0001-4000-8000-000000000041",
      "section": "detail",
      "text": "PCR / Abschluss",
      "x": 40,
      "y": 336,
      "width": 240,
      "height": 16,
      "fontSize": 12,
      "align": "left",
      "bold": true,
      "italic": false,
      "underline": false,
      "color": "#111827",
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "c0000001-0001-4000-8000-000000000042",
      "section": "detail",
      "text": "Problem",
      "x": 40,
      "y": 358,
      "width": 120,
      "height": 14,
      "fontSize": 9,
      "align": "left",
      "bold": true,
      "italic": false,
      "underline": false,
      "color": "#111827",
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "c0000001-0001-4000-8000-000000000043",
      "section": "detail",
      "text": "{{problemLabel}}",
      "x": 160,
      "y": 358,
      "width": 395,
      "height": 14,
      "fontSize": 10,
      "align": "left",
      "bold": false,
      "italic": false,
      "underline": false,
      "color": "#111827",
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "c0000001-0001-4000-8000-000000000044",
      "section": "detail",
      "text": "Ursache",
      "x": 40,
      "y": 378,
      "width": 120,
      "height": 14,
      "fontSize": 9,
      "align": "left",
      "bold": true,
      "italic": false,
      "underline": false,
      "color": "#111827",
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "c0000001-0001-4000-8000-000000000045",
      "section": "detail",
      "text": "{{causeLabel}}",
      "x": 160,
      "y": 378,
      "width": 395,
      "height": 14,
      "fontSize": 10,
      "align": "left",
      "bold": false,
      "italic": false,
      "underline": false,
      "color": "#111827",
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "c0000001-0001-4000-8000-000000000046",
      "section": "detail",
      "text": "Maßnahme",
      "x": 40,
      "y": 398,
      "width": 120,
      "height": 14,
      "fontSize": 9,
      "align": "left",
      "bold": true,
      "italic": false,
      "underline": false,
      "color": "#111827",
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "c0000001-0001-4000-8000-000000000047",
      "section": "detail",
      "text": "{{remedyLabel}}",
      "x": 160,
      "y": 398,
      "width": 395,
      "height": 14,
      "fontSize": 10,
      "align": "left",
      "bold": false,
      "italic": false,
      "underline": false,
      "color": "#111827",
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "c0000001-0001-4000-8000-000000000048",
      "section": "detail",
      "text": "Erledigt durch",
      "x": 40,
      "y": 418,
      "width": 120,
      "height": 14,
      "fontSize": 9,
      "align": "left",
      "bold": true,
      "italic": false,
      "underline": false,
      "color": "#111827",
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "c0000001-0001-4000-8000-000000000049",
      "section": "detail",
      "text": "{{doneByLabel}}",
      "x": 160,
      "y": 418,
      "width": 395,
      "height": 14,
      "fontSize": 10,
      "align": "left",
      "bold": false,
      "italic": false,
      "underline": false,
      "color": "#111827",
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "c0000001-0001-4000-8000-000000000050",
      "section": "detail",
      "text": "Pause-Bemerkung",
      "x": 40,
      "y": 442,
      "width": 515,
      "height": 14,
      "fontSize": 9,
      "align": "left",
      "bold": true,
      "italic": false,
      "underline": false,
      "color": "#111827",
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "c0000001-0001-4000-8000-000000000051",
      "section": "detail",
      "text": "{{pauseRemark}}",
      "x": 40,
      "y": 460,
      "width": 515,
      "height": 32,
      "fontSize": 10,
      "align": "left",
      "bold": false,
      "italic": false,
      "underline": false,
      "color": "#111827",
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "c0000001-0001-4000-8000-000000000060",
      "section": "detail",
      "text": "",
      "x": 40,
      "y": 502,
      "width": 515,
      "height": 1,
      "fontSize": 10,
      "align": "left",
      "bold": false,
      "italic": false,
      "underline": false,
      "color": "#111827",
      "kind": "hline",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "c0000001-0001-4000-8000-000000000061",
      "section": "detail",
      "text": "Verknüpfungen",
      "x": 40,
      "y": 514,
      "width": 240,
      "height": 16,
      "fontSize": 12,
      "align": "left",
      "bold": true,
      "italic": false,
      "underline": false,
      "color": "#111827",
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "c0000001-0001-4000-8000-000000000062",
      "section": "detail",
      "text": "Originalauftrag",
      "x": 40,
      "y": 536,
      "width": 120,
      "height": 14,
      "fontSize": 9,
      "align": "left",
      "bold": true,
      "italic": false,
      "underline": false,
      "color": "#111827",
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "c0000001-0001-4000-8000-000000000063",
      "section": "detail",
      "text": "{{originalWoLabel}}",
      "x": 160,
      "y": 536,
      "width": 395,
      "height": 14,
      "fontSize": 10,
      "align": "left",
      "bold": false,
      "italic": false,
      "underline": false,
      "color": "#111827",
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "c0000001-0001-4000-8000-000000000064",
      "section": "detail",
      "text": "Wartungsplan",
      "x": 40,
      "y": 556,
      "width": 120,
      "height": 14,
      "fontSize": 9,
      "align": "left",
      "bold": true,
      "italic": false,
      "underline": false,
      "color": "#111827",
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "c0000001-0001-4000-8000-000000000065",
      "section": "detail",
      "text": "{{maintenancePlanLabel}}",
      "x": 160,
      "y": 556,
      "width": 395,
      "height": 14,
      "fontSize": 10,
      "align": "left",
      "bold": false,
      "italic": false,
      "underline": false,
      "color": "#111827",
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "c0000001-0001-4000-8000-000000000066",
      "section": "detail",
      "text": "Inspektionsrunde",
      "x": 40,
      "y": 576,
      "width": 120,
      "height": 14,
      "fontSize": 9,
      "align": "left",
      "bold": true,
      "italic": false,
      "underline": false,
      "color": "#111827",
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "c0000001-0001-4000-8000-000000000067",
      "section": "detail",
      "text": "{{inspectionRoundLabel}}",
      "x": 160,
      "y": 576,
      "width": 395,
      "height": 14,
      "fontSize": 10,
      "align": "left",
      "bold": false,
      "italic": false,
      "underline": false,
      "color": "#111827",
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "c0000001-0001-4000-8000-000000000070",
      "section": "detail",
      "text": "",
      "x": 40,
      "y": 600,
      "width": 515,
      "height": 1,
      "fontSize": 10,
      "align": "left",
      "bold": false,
      "italic": false,
      "underline": false,
      "color": "#111827",
      "kind": "hline",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "c0000001-0001-4000-8000-000000000071",
      "section": "detail",
      "text": "Protokoll",
      "x": 40,
      "y": 612,
      "width": 240,
      "height": 16,
      "fontSize": 12,
      "align": "left",
      "bold": true,
      "italic": false,
      "underline": false,
      "color": "#111827",
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "c0000001-0001-4000-8000-000000000072",
      "section": "detail",
      "text": "Erstellt",
      "x": 40,
      "y": 634,
      "width": 120,
      "height": 14,
      "fontSize": 9,
      "align": "left",
      "bold": true,
      "italic": false,
      "underline": false,
      "color": "#111827",
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "c0000001-0001-4000-8000-000000000073",
      "section": "detail",
      "text": "{{createdAt}}  ·  {{createdBy}}",
      "x": 160,
      "y": 634,
      "width": 395,
      "height": 14,
      "fontSize": 10,
      "align": "left",
      "bold": false,
      "italic": false,
      "underline": false,
      "color": "#111827",
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "c0000001-0001-4000-8000-000000000074",
      "section": "detail",
      "text": "Geändert",
      "x": 40,
      "y": 654,
      "width": 120,
      "height": 14,
      "fontSize": 9,
      "align": "left",
      "bold": true,
      "italic": false,
      "underline": false,
      "color": "#111827",
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "c0000001-0001-4000-8000-000000000075",
      "section": "detail",
      "text": "{{updatedAt}}  ·  {{updatedBy}}",
      "x": 160,
      "y": 654,
      "width": 395,
      "height": 14,
      "fontSize": 10,
      "align": "left",
      "bold": false,
      "italic": false,
      "underline": false,
      "color": "#111827",
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "c0000001-0001-4000-8000-000000000080",
      "section": "footer",
      "text": "Athene CMMS  ·  Auftrags-Report  ·  Seite {{_pageNumber}}",
      "x": 40,
      "y": 8,
      "width": 360,
      "height": 16,
      "fontSize": 9,
      "align": "left",
      "bold": false,
      "italic": false,
      "underline": false,
      "color": "#111827",
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    },
    {
      "id": "c0000001-0001-4000-8000-000000000081",
      "section": "footer",
      "text": "ID: {{id}}",
      "x": 360,
      "y": 8,
      "width": 195,
      "height": 16,
      "fontSize": 8,
      "align": "right",
      "bold": false,
      "italic": false,
      "underline": false,
      "color": "#111827",
      "kind": "text",
      "sourceField": "",
      "dateFormat": ""
    }
  ]
}$report_layout$::jsonb
WHERE "key" = 'work-order-detail-report';
